"""Type stubs for python-decouple."""

from collections import OrderedDict
from typing import Any, overload

class UndefinedValueError(Exception): ...
class Undefined: ...

undefined: Undefined

class Config:
    repository: Any
    def __init__(self, repository: RepositoryEmpty) -> None: ...
    @overload
    def get(self, option: str) -> str: ...
    @overload
    def get(self, option: str, *, cast: type[bool]) -> bool: ...
    @overload
    def get(self, option: str, *, cast: type[int]) -> int: ...
    @overload
    def get(self, option: str, *, cast: type[float]) -> float: ...
    @overload
    def get(self, option: str, *, cast: type[str]) -> str: ...
    @overload
    def get(self, option: str, default: str) -> str: ...
    @overload
    def get(self, option: str, default: str, cast: type[bool]) -> bool: ...
    @overload
    def get(self, option: str, default: str, cast: type[int]) -> int: ...
    @overload
    def get(self, option: str, default: str, cast: type[float]) -> float: ...
    @overload
    def get(self, option: str, default: str, cast: type[str]) -> str: ...
    @overload
    def get(self, option: str, *, default: str) -> str: ...
    @overload
    def get(self, option: str, *, default: str, cast: type[bool]) -> bool: ...
    @overload
    def get(self, option: str, *, default: str, cast: type[int]) -> int: ...
    @overload
    def get(self, option: str, *, default: str, cast: type[float]) -> float: ...
    @overload
    def get(self, option: str, *, default: str, cast: type[str]) -> str: ...
    @overload
    def get[T](self, option: str, default: T) -> str | T: ...
    @overload
    def get[T](self, option: str, *, default: T) -> str | T: ...
    @overload
    def get[T](self, option: str, default: Any = ..., cast: type[T] = ...) -> T: ...
    @overload
    def __call__(self, option: str) -> str: ...
    @overload
    def __call__(self, option: str, *, cast: type[bool]) -> bool: ...
    @overload
    def __call__(self, option: str, *, cast: type[int]) -> int: ...
    @overload
    def __call__(self, option: str, *, cast: type[float]) -> float: ...
    @overload
    def __call__(self, option: str, *, cast: type[str]) -> str: ...
    @overload
    def __call__(self, option: str, default: str) -> str: ...
    @overload
    def __call__(self, option: str, default: str, cast: type[bool]) -> bool: ...
    @overload
    def __call__(self, option: str, default: str, cast: type[int]) -> int: ...
    @overload
    def __call__(self, option: str, default: str, cast: type[float]) -> float: ...
    @overload
    def __call__(self, option: str, default: str, cast: type[str]) -> str: ...
    @overload
    def __call__(self, option: str, *, default: str) -> str: ...
    @overload
    def __call__(self, option: str, *, default: str, cast: type[bool]) -> bool: ...
    @overload
    def __call__(self, option: str, *, default: str, cast: type[int]) -> int: ...
    @overload
    def __call__(self, option: str, *, default: str, cast: type[float]) -> float: ...
    @overload
    def __call__(self, option: str, *, default: str, cast: type[str]) -> str: ...
    @overload
    def __call__[T](self, option: str, default: T) -> str | T: ...
    @overload
    def __call__[T](self, option: str, *, default: T) -> str | T: ...
    @overload
    def __call__[T](self, option: str, default: Any = ..., cast: type[T] = ...) -> T: ...

class RepositoryEmpty:
    def __init__(self, source: str = ..., encoding: str = ...) -> None: ...
    def __contains__(self, key: str) -> bool: ...
    def __getitem__(self, key: str) -> str | None: ...

class RepositoryIni(RepositoryEmpty):
    SECTION: str
    def __init__(self, source: str, encoding: str = ...) -> None: ...

class RepositoryEnv(RepositoryEmpty):
    data: dict[str, str]
    def __init__(self, source: str, encoding: str = ...) -> None: ...

class RepositorySecret(RepositoryEmpty):
    data: dict[str, str]
    def __init__(self, source: str = ...) -> None: ...

class AutoConfig:
    SUPPORTED: OrderedDict[str, type[RepositoryEmpty]]
    encoding: str
    config: Config | None
    def __init__(self, search_path: str | None = ...) -> None: ...
    @overload
    def __call__(self, option: str) -> str: ...
    @overload
    def __call__(self, option: str, *, cast: type[bool]) -> bool: ...
    @overload
    def __call__(self, option: str, *, cast: type[int]) -> int: ...
    @overload
    def __call__(self, option: str, *, cast: type[float]) -> float: ...
    @overload
    def __call__(self, option: str, *, cast: type[str]) -> str: ...
    @overload
    def __call__(self, option: str, default: str) -> str: ...
    @overload
    def __call__(self, option: str, default: str, cast: type[bool]) -> bool: ...
    @overload
    def __call__(self, option: str, default: str, cast: type[int]) -> int: ...
    @overload
    def __call__(self, option: str, default: str, cast: type[float]) -> float: ...
    @overload
    def __call__(self, option: str, default: str, cast: type[str]) -> str: ...
    @overload
    def __call__(self, option: str, *, default: str) -> str: ...
    @overload
    def __call__(self, option: str, *, default: str, cast: type[bool]) -> bool: ...
    @overload
    def __call__(self, option: str, *, default: str, cast: type[int]) -> int: ...
    @overload
    def __call__(self, option: str, *, default: str, cast: type[float]) -> float: ...
    @overload
    def __call__(self, option: str, *, default: str, cast: type[str]) -> str: ...
    @overload
    def __call__[T](self, option: str, default: T) -> str | T: ...
    @overload
    def __call__[T](self, option: str, *, default: T) -> str | T: ...
    @overload
    def __call__[T](self, option: str, default: Any = ..., cast: type[T] = ...) -> T: ...

config: AutoConfig

class Csv:
    cast: type[Any]
    delimiter: str
    strip: str
    post_process: type[Any]
    def __init__(
        self,
        cast: type[Any] = ...,
        delimiter: str = ...,
        strip: str = ...,
        post_process: type[Any] = ...,
    ) -> None: ...
    def __call__(self, value: str | None) -> list[Any]: ...

class Choices:
    flat: list[Any]
    cast: type[Any]
    choices: list[tuple[Any, Any]]
    def __init__(
        self,
        flat: list[Any] | None = ...,
        cast: type[Any] = ...,
        choices: list[tuple[Any, Any]] | None = ...,
    ) -> None: ...
    def __call__(self, value: Any) -> Any: ...

def strtobool(value: str | bool) -> bool: ...
